baseURL: "https://tplog.github.io"
languageCode: "en-US"
title: "tplog"
pagination: 10

params:
  smartToc: true
  author: "tplog"
  keywords:
    - "Technology"
    - "Code"
    - "Program"
    - "Linux"
  description: ""

menu:
  footer:
    - name: "about"
      url: "/about"
      weight: 1
    - name: "archives"
      url: "/"
      weight: 2
    - name: "tags"
      url: "/tags/"
      weight: 3

  icon:
    - name: "rss"
      url: "/index.xml"
      weight: 1
    - name: "github"
      url: "https://github.com/tplog"
      weight: 2
